filebeat.inputs:
  - type: filestream
    id: my-application-logs
    enabled: true
    paths:
      - "${METRICS_LOGS_DIR:/var/log}/${METRICS_LOGFILE_MATCH:*log*}"

filebeat.modules:
  - module: nginx
    access:
      enabled: true
      var.paths: ["${NGINX_LOGS_DIR:/var/log}/nginx/access.log*"]
    error:
      enabled: true
      var.paths: ["${NGINX_LOGS_DIR:/var/log}/nginx/error.log*"]

output.logstash:
  hosts: ["logstash:5044"]
  username: 'elastic'
  password: '${ELASTIC_PASSWORD}'