filebeat.inputs:
  - type: filestream
    id: my-application-logs
    enabled: true
    paths:
      - "${METRICS_LOGS_DIR:/var/log}/${METRICS_LOGFILE_MATCH:*log*}"
      - "${NGINX_LOGS_DIR:/var/log}/*log*}"

output.logstash:
  hosts: ["logstash:5044"]
  username: 'elastic'
  password: '${ELASTIC_PASSWORD}'