version: '3.7'
# extends, so run with `docker compose -f docker-compose.yml -f docker-compose-prod.yml
services:
  nginx:
    volumes: 
      - ./nginx/prod_conf.d_templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,Z
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "443:443"
      - "80:80"
    environment:
      NGINX_ENVSUBST_TEMPLATE_DIR: /etc/nginx/templates
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      METRICS_HOSTNAME: usagemetrics.hydroshare.org
      CADDY_SUBDOMAIN: ${CADDY_SUBDOMAIN:-caddy}
      ES_SUBDOMAIN: ${ES_SUBDOMAIN:-es}
      KIBANA_SUBDOMAIN: ${KIBANA_SUBDOMAIN:-kibana}
      LOGSTASH_SUBDOMAIN: ${LOGSTASH_SUBDOMAIN:-logstash}
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    depends_on:
      - nginx
    user: root
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
