---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/6.8/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
# elasticsearch.hosts: [ http://elasticsearch:9200 ]

# The default application to load.
kibana.defaultAppId: "dashboard/Aggregate-Reporting-of-HydroShare-Users"

# Enables you specify a file where Kibana stores log output.
# TODO: uncomment for prod
# logging.dest: /var/log/kibana/kibana.log

# Set the value of this setting to true to log all events, including system usage information 
# and all requests.
logging.verbose: false

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: changeme
