---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana-docker/blob/5.6/build/kibana/config/kibana.yml
#
server.name: kibana
elasticsearch.url: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: false
server.host: "localhost"
# elasticsearch.hosts: [ http://elasticsearch:9200 ]

# The default application to load.
kibana.defaultAppId: "dashboard/Aggregate-Reporting-of-HydroShare-Users"

# Enables you specify a file where Kibana stores log output.
# TODO: uncomment for prod
# logging.dest: /var/log/kibana/kibana.log

# Set the value of this setting to true to log all events, including system usage information 
# and all requests.
logging.verbose: false


monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

## X-Pack security credentials
#
elasticsearch.username: kibana
elasticsearch.password: changeme
