# Figure styling
# ------------------
# colors: 'b': blue, 'g': green, 'r': red, 'c': cyan, 'm': magenta, 'y': yellow, 'k': black, 'w': white
# linestyles: supported values are '-', '--', '-.', ':', 'None', ' ', '', 'solid', 'dashed', 'dashdot', 'dotted'
# Additional configuration via rc_params: https://matplotlib.org/stable/tutorials/introductory/customizing.html
# ------------------
# User Figures
# - types: active, total, new, returning
# ------------------
# Resource Figures
# - types: total
# ------------------
# Organization Figures
# - types: total, us_universities, international_universities, cuahsi_members
# ------------------

report:
  collect_data: True
  input_directory: 11.27.2022
  output_directory: 11.27.2022/report
  creator: Devin Cowan
  date_created: 11/27/2022
  title: Experimental HS Usage Report
  description: |
    Exploratory figures and statistics about HydroShare users, their activity, and their data.
  css: |
    .preamble {
      background-color: #d3d3d359;
      padding: 1 50;
    }
    .caption {
      font-size: 14pt;
      padding: 0 50;
    }
    .title-block {
      padding: 10 50;
    }
    .figure-title {
      display: inline-block;
    }
    .figure-data {
      display: inline-block;
      padding: 0 50;
      vertical-align: middle;
    }
    .dataframe {
      border-collapse: collapse !important;
      width: 100%;
      margin: 10px;
    }
    .dataframe * {
      max-width: 100%;
      margin-bottom: 18px;
      background-color: transparent;
    }
    .dataframe table {
      border-spacing: 0;
      border-top-width: 1px;
      border-right-width: 1px;
      border-bottom-width: 1px;
      border-left-width: 1px;
    }
    .dataframe th {
      background: #eee;
      text-align: center;
      padding: 5px;
    }
    .dataframe td {
      vertical-align: middle;
      text-align: center;
      border-color: inherit;
      padding: 5px;
    }
    .dataframe tr {
      display: table-row;
      vertical-align: inherit;
      border-color: inherit;
    }
    .dataframe > tbody > tr:nth-of-type(odd) {
      background-color: #f1eeee;
    }


metrics:
  doi-monthly-user-type:
    metric_type: doi
    start_time: 01-01-2015
#    end_time: 11-01-2022
    aggregation: 1M
    save_data: True
    series:
      - type: publications_by_usr_type
        label: Published resources per month
        linestyle: '-'
    figure_configuration:
      type: line
      title: Cumulative Resources with DOI's over time, by User Type.
      caption: |
        Digital object identifiers (DOIs) created over time, separated by user type, aggregated monthly, and summed cumulatively.
      rcParams:
        axes.titlesize: 24
        axes.labelsize: 16
        legend.fontsize: 12
        figure.figsize: 12, 7
      axis:
        xlabel: Publication Date
        ylabel: Number of Published Resources
        ylim: (0.0, None)
      figure:
        annotate_series: True
        grid: True
        legend: True
    
  doi-monthly-org-type:
    metric_type: doi
    start_time: 01-01-2015
#    end_time: 11-01-2022
    aggregation: 1M
    save_data: True
    series:
      - type: publications_by_org_type
        label: Published resources per month
        linestyle: '-'
    figure_configuration:
      type: line
      title: Cumulative Resources with DOI's over time, by Organization Type.
      caption: |
        Digital object identifiers (DOIs) created over time, separated by user organization type, aggregated monthly, and summed cumulatively.
      rcParams:
        axes.titlesize: 24
        axes.labelsize: 16
        legend.fontsize: 12
        figure.figsize: 12, 7
      axis:
        xlabel: Publication Date
        ylabel: Number of Published Resources
        ylim: (0.0, None)
      figure:
        annotate_series: True
        grid: True
        legend: True

  doi-pie-org-type:
    metric_type: doi
    start_time: 01-01-2015
#    end_time: 11-01-2022
    save_data: True
    series:
      - type: orgpie
        exclude:
          - None
        publication_threshold: 1
    figure_configuration:
      type: pie
      title: Distribution of Publications by Specified Org Types
      caption: |
        The distribution of HydroShare publications based on how the user defined "org type" type in their profile.
      rcParams:
        axes.titlesize: 24
        axes.labelsize: 16
        legend.fontsize: 12
        figure.figsize: 10, 7
      axis:
        xlabel: ""
        ylabel: ""
  
  doi-organizations-table:
    metric_type: doi
    start_time: 01-01-2015
#    end_time: 11-01-2022
    aggregation: M
    save_data: True
    return_type: html # can be html or img
    filename: organizations-table.html
    series:
      - type: orgtable
        label: Test Organizations
        exclude:
          - None
        publication_threshold: 1
    figure_configuration:
      type: table_html
      title: Publications by Org Type
      caption: |
        The distribution of HydroShare publications based on how the user defined "org type" type in their profile.
      rcParams:
        figure.figsize: 10, 20

#   organizations-line:
#     metric_type: organization
#     start_time: 01-01-2015
# #    end_time: 11-01-2022
#     aggregation: 1D
#     save_data: True
#     series:
#       - type: org_type
#         label: Organizations
#         linestyle: '-'
#         users_threshold: 25
#     figure_configuration:
#       type: line
#       title: Orgs over time
#       caption: Orgs
#       rcParams:
#         axes.titlesize: 24
#         axes.labelsize: 16
#         legend.fontsize: 12
#         figure.figsize: 12, 7
#       axis:
#         xlabel: Account Creation Date
#         ylabel: Number of Organizations
#         ylim: (0.0, None)
#       figure:
#         annotate_series: True
#         grid: True
#         legend: True

#   organizations-table:
#     metric_type: organization
#     start_time: 01-01-2015
# #    end_time: 11-01-2022
#     aggregation: M
#     save_data: True
#     return_type: html # can be html or img
#     filename: organizations-table.html
#     series:
#       - type: total_table
#         label: Test Organizations
#         users_threshold: 25
#     figure_configuration:
#       type: table_html
#       title: Organizations
#       caption: |
#         This table is orgs
#       rcParams:
#         figure.figsize: 10, 20

  activity-table:
    metric_type: activity
    start_time: 01-01-2015
#    end_time: 11-01-2022
    aggregation: M
    save_data: True
    return_type: html # can be html or img
    filename: activity-table.html
    series:
      - type: quarterly_activity_table
        label: Quarterly Activity
    figure_configuration:
      type: table_html
      title: Quarterly User Actions Summarized by Type
      caption: |
        This table contains a quarterly summary of total user actions. 
      rcParams:
        figure.figsize: 10, 20